#!/usr/bin/env python
"""
Generate Robot Framework tests from websites_100.yaml

This script generates 100 individual test cases (no template, no FOR loop)
from the YAML file containing website URLs.

Usage:
    python generate_tests.py > test_100_websites.robot
    
Or directly:
    python generate_tests.py
"""

import yaml
import sys


def load_websites(yaml_file='websites_100.yaml'):
    """Load websites from YAML file."""
    with open(yaml_file, 'r') as f:
        data = yaml.safe_load(f)
    return data['websites']


def generate_test_case(site):
    """
    Generate a single Robot Framework test case.
    
    Each test is exactly the same structure:
    - Open Website
    - Collect Elements
    - Take Screenshot  
    - Annotate with BBox
    """
    test = f"""
Test {site['name']}
    [Documentation]    Category: {site['category']} | URL: {site['url']}
    [Tags]    {site['category']}    100websites
    
    Open Website    {site['url']}
    
    ${{elements}}=    Connector.Collect UI Candidates
    Log Many    @{{elements}}
    
    ${{screenshot}}=    Take Screenshot    filename={site['name']}.png    fullPage=True
    ${{annotated}}=    Draw And Log Elements    ${{elements}}    ${{screenshot}}
    
    [Teardown]    Close Browser
"""
    return test


def generate_robot_file(websites):
    """Generate complete Robot Framework file with 100 tests."""
    
    header = """*** Settings ***
Documentation    Test JSQuery collector on 100 diverse websites
...              This file is AUTO-GENERATED by generate_tests.py
...              Categories: demo(20), simple(20), text(15), images(15), spa(15), social(10), ecommerce(5)
Library          Browser
Library          Agent.platforms._webconnector.WebConnectorRF    js_query    AS    Connector
Library          tests/atest/compounent/BBoxVisualizer.py
Resource         ${EXECDIR}/tests/atest/browsers/config.robot

Suite Setup      Log    Starting test suite on 100 websites
Suite Teardown   Log    ✅ Test suite complete

*** Test Cases ***"""
    
    # Generate all test cases
    tests = [generate_test_case(site) for site in websites]
    
    # Combine header and tests
    content = header + ''.join(tests)
    
    return content


def main():
    """Main function."""
    print("Loading websites from websites_100.yaml...")
    websites = load_websites()
    
    print(f"Found {len(websites)} websites")
    
    # Count by category
    categories = {}
    for site in websites:
        cat = site['category']
        categories[cat] = categories.get(cat, 0) + 1
    
    print("Distribution:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")
    
    print("\nGenerating Robot Framework file...")
    content = generate_robot_file(websites)
    
    # Write to file
    output_file = 'test_100_websites.robot'
    with open(output_file, 'w') as f:
        f.write(content)
    
    print(f"✅ Generated {output_file}")
    print(f"   Total lines: {len(content.splitlines())}")
    print(f"   Total tests: {len(websites)}")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())






