*** Settings ***
Documentation    Test JSQuery collector on 100 diverse websites
...              This file is AUTO-GENERATED by generate_tests.py
...              Categories: demo(20), simple(20), text(15), images(15), spa(15), social(10), ecommerce(5)
Library          Browser
Library          Agent.platforms._webconnector.WebConnectorRF    axtree    AS    Connector
Library          tests/atest/compounent/BBoxVisualizer.py
Resource         ${EXECDIR}/tests/atest/browsers/config.robot

Suite Setup      Log    Starting test suite on 100 websites
Suite Teardown   Log    ✅ Test suite complete

*** Test Cases ***
Test HerokuApp_Login
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/login
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/login
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Login.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test SauceDemo
    [Documentation]    Category: demo | URL: https://www.saucedemo.com
    [Tags]    demo    100websites
    
    Open Website    https://www.saucedemo.com
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=SauceDemo.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test DemoQA
    [Documentation]    Category: demo | URL: https://demoqa.com
    [Tags]    demo    100websites
    
    Open Website    https://demoqa.com
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=DemoQA.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_Dropdown
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/dropdown
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/dropdown
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Dropdown.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_Checkboxes
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/checkboxes
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/checkboxes
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Checkboxes.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_Inputs
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/inputs
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/inputs
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Inputs.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_Upload
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/upload
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/upload
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Upload.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_Tables
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/tables
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/tables
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_Tables.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_IFrame
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/iframe
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/iframe
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_IFrame.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

Test HerokuApp_DynamicLoading
    [Documentation]    Category: demo | URL: https://the-internet.herokuapp.com/dynamic_loading/1
    [Tags]    demo    100websites
    
    Open Website    https://the-internet.herokuapp.com/dynamic_loading/1
    
    ${elements}=    Connector.Collect UI Candidates
    Log Many    @{elements}
    
    ${screenshot}=    Take Screenshot    filename=HerokuApp_DynamicLoading.png    fullPage=True
    ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
    [Teardown]    Close Browser

# Test AutomationExercise
#     [Documentation]    Category: demo | URL: https://automationexercise.com
#     [Tags]    demo    100websites
    
#     Open Website    https://automationexercise.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=AutomationExercise.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test XYZ_Bank
#     [Documentation]    Category: demo | URL: https://www.globalsqa.com/angularJs-protractor/BankingProject
#     [Tags]    demo    100websites
    
#     Open Website    https://www.globalsqa.com/angularJs-protractor/BankingProject
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=XYZ_Bank.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test PHPTravels_Demo
#     [Documentation]    Category: demo | URL: https://phptravels.com/demo
#     [Tags]    demo    100websites
    
#     Open Website    https://phptravels.com/demo
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=PHPTravels_Demo.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test OpenCart_Demo
#     [Documentation]    Category: demo | URL: https://demo.opencart.com
#     [Tags]    demo    100websites
    
#     Open Website    https://demo.opencart.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=OpenCart_Demo.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test NopCommerce_Demo
#     [Documentation]    Category: demo | URL: https://demo.nopcommerce.com
#     [Tags]    demo    100websites
    
#     Open Website    https://demo.nopcommerce.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=NopCommerce_Demo.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Magento_Demo
#     [Documentation]    Category: demo | URL: https://magento.softwaretestingboard.com
#     [Tags]    demo    100websites
    
#     Open Website    https://magento.softwaretestingboard.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Magento_Demo.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test ExpandTesting_Practice
#     [Documentation]    Category: demo | URL: https://practice.expandtesting.com
#     [Tags]    demo    100websites
    
#     Open Website    https://practice.expandtesting.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=ExpandTesting_Practice.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test EvilTester_Pages
#     [Documentation]    Category: demo | URL: https://testpages.eviltester.com/styled/index.html
#     [Tags]    demo    100websites
    
#     Open Website    https://testpages.eviltester.com/styled/index.html
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=EvilTester_Pages.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test AutomationCamp
#     [Documentation]    Category: demo | URL: https://play1.automationcamp.ir/index.html
#     [Tags]    demo    100websites
    
#     Open Website    https://play1.automationcamp.ir/index.html
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=AutomationCamp.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Example
#     [Documentation]    Category: simple | URL: https://example.com
#     [Tags]    simple    100websites
    
#     Open Website    https://example.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Example.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test CERN_FirstWebsite
#     [Documentation]    Category: simple | URL: https://info.cern.ch
#     [Tags]    simple    100websites
    
#     Open Website    https://info.cern.ch
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=CERN_FirstWebsite.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test W3C
#     [Documentation]    Category: simple | URL: https://www.w3.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.w3.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=W3C.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test IANA
#     [Documentation]    Category: simple | URL: https://www.iana.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.iana.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=IANA.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test RFC_Editor
#     [Documentation]    Category: simple | URL: https://www.rfc-editor.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.rfc-editor.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=RFC_Editor.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Kernel_Org
#     [Documentation]    Category: simple | URL: https://www.kernel.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.kernel.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Kernel_Org.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Debian
#     [Documentation]    Category: simple | URL: https://www.debian.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.debian.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Debian.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Python_Org
#     [Documentation]    Category: simple | URL: https://www.python.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.python.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Python_Org.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test NPM
#     [Documentation]    Category: simple | URL: https://www.npmjs.com
#     [Tags]    simple    100websites
    
#     Open Website    https://www.npmjs.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=NPM.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test PyPI
#     [Documentation]    Category: simple | URL: https://pypi.org
#     [Tags]    simple    100websites
    
#     Open Website    https://pypi.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=PyPI.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Rust_Lang
#     [Documentation]    Category: simple | URL: https://www.rust-lang.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.rust-lang.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Rust_Lang.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Go_Lang
#     [Documentation]    Category: simple | URL: https://golang.org
#     [Tags]    simple    100websites
    
#     Open Website    https://golang.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Go_Lang.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Ruby_Lang
#     [Documentation]    Category: simple | URL: https://www.ruby-lang.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.ruby-lang.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Ruby_Lang.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test PHP_Net
#     [Documentation]    Category: simple | URL: https://www.php.net
#     [Tags]    simple    100websites
    
#     Open Website    https://www.php.net
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=PHP_Net.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Perl_Org
#     [Documentation]    Category: simple | URL: https://www.perl.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.perl.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Perl_Org.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Scala_Lang
#     [Documentation]    Category: simple | URL: https://www.scala-lang.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.scala-lang.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Scala_Lang.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Kotlin_Lang
#     [Documentation]    Category: simple | URL: https://kotlinlang.org
#     [Tags]    simple    100websites
    
#     Open Website    https://kotlinlang.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Kotlin_Lang.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test SQLite
#     [Documentation]    Category: simple | URL: https://www.sqlite.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.sqlite.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=SQLite.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test PostgreSQL
#     [Documentation]    Category: simple | URL: https://www.postgresql.org
#     [Tags]    simple    100websites
    
#     Open Website    https://www.postgresql.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=PostgreSQL.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Nginx
#     [Documentation]    Category: simple | URL: https://www.nginx.com
#     [Tags]    simple    100websites
    
#     Open Website    https://www.nginx.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Nginx.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_Python
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Python_(programming_language)
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Python_(programming_language)
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_Python.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_AI
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Artificial_intelligence
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Artificial_intelligence
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_AI.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_JavaScript
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/JavaScript
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/JavaScript
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_JavaScript.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_WebDev
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Web_development
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Web_development
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_WebDev.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_Testing
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Software_testing
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Software_testing
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_Testing.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_ML
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Machine_learning
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Machine_learning
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_ML.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_DataScience
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Data_science
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Data_science
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_DataScience.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_Cloud
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Cloud_computing
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Cloud_computing
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_Cloud.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_Blockchain
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Blockchain
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Blockchain
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_Blockchain.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Wikipedia_Cybersecurity
#     [Documentation]    Category: text | URL: https://en.wikipedia.org/wiki/Cybersecurity
#     [Tags]    text    100websites
    
#     Open Website    https://en.wikipedia.org/wiki/Cybersecurity
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Wikipedia_Cybersecurity.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test BBC_News
#     [Documentation]    Category: text | URL: https://www.bbc.com/news
#     [Tags]    text    100websites
    
#     Open Website    https://www.bbc.com/news
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=BBC_News.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Guardian_Tech
#     [Documentation]    Category: text | URL: https://www.theguardian.com/technology
#     [Tags]    text    100websites
    
#     Open Website    https://www.theguardian.com/technology
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Guardian_Tech.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test DevTo
#     [Documentation]    Category: text | URL: https://dev.to
#     [Tags]    text    100websites
    
#     Open Website    https://dev.to
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=DevTo.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test FreeCodeCamp_News
#     [Documentation]    Category: text | URL: https://www.freecodecamp.org/news
#     [Tags]    text    100websites
    
#     Open Website    https://www.freecodecamp.org/news
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=FreeCodeCamp_News.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Smashing_Magazine
#     [Documentation]    Category: text | URL: https://www.smashingmagazine.com
#     [Tags]    text    100websites
    
#     Open Website    https://www.smashingmagazine.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Smashing_Magazine.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Unsplash
#     [Documentation]    Category: images | URL: https://unsplash.com
#     [Tags]    images    100websites
    
#     Open Website    https://unsplash.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Unsplash.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Pexels
#     [Documentation]    Category: images | URL: https://www.pexels.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.pexels.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Pexels.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Pixabay
#     [Documentation]    Category: images | URL: https://pixabay.com
#     [Tags]    images    100websites
    
#     Open Website    https://pixabay.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Pixabay.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Flickr_Explore
#     [Documentation]    Category: images | URL: https://www.flickr.com/explore
#     [Tags]    images    100websites
    
#     Open Website    https://www.flickr.com/explore
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Flickr_Explore.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test 500px
#     [Documentation]    Category: images | URL: https://500px.com
#     [Tags]    images    100websites
    
#     Open Website    https://500px.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=500px.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Behance
#     [Documentation]    Category: images | URL: https://www.behance.net
#     [Tags]    images    100websites
    
#     Open Website    https://www.behance.net
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Behance.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Dribbble
#     [Documentation]    Category: images | URL: https://dribbble.com
#     [Tags]    images    100websites
    
#     Open Website    https://dribbble.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Dribbble.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Awwwards
#     [Documentation]    Category: images | URL: https://www.awwwards.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.awwwards.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Awwwards.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test DeviantArt
#     [Documentation]    Category: images | URL: https://www.deviantart.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.deviantart.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=DeviantArt.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test ArtStation
#     [Documentation]    Category: images | URL: https://www.artstation.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.artstation.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=ArtStation.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Shutterstock
#     [Documentation]    Category: images | URL: https://www.shutterstock.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.shutterstock.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Shutterstock.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Adobe_Stock
#     [Documentation]    Category: images | URL: https://stock.adobe.com
#     [Tags]    images    100websites
    
#     Open Website    https://stock.adobe.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Adobe_Stock.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Getty_Images
#     [Documentation]    Category: images | URL: https://www.gettyimages.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.gettyimages.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Getty_Images.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test iStock
#     [Documentation]    Category: images | URL: https://www.istockphoto.com
#     [Tags]    images    100websites
    
#     Open Website    https://www.istockphoto.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=iStock.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Burst_Shopify
#     [Documentation]    Category: images | URL: https://burst.shopify.com
#     [Tags]    images    100websites
    
#     Open Website    https://burst.shopify.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Burst_Shopify.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test React_ShoppingCart
#     [Documentation]    Category: spa | URL: https://react-shopping-cart-67954.firebaseapp.com
#     [Tags]    spa    100websites
    
#     Open Website    https://react-shopping-cart-67954.firebaseapp.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=React_ShoppingCart.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test TodoMVC_React
#     [Documentation]    Category: spa | URL: https://todomvc.com/examples/react
#     [Tags]    spa    100websites
    
#     Open Website    https://todomvc.com/examples/react
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=TodoMVC_React.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test TodoMVC_Vue
#     [Documentation]    Category: spa | URL: https://todomvc.com/examples/vue
#     [Tags]    spa    100websites
    
#     Open Website    https://todomvc.com/examples/vue
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=TodoMVC_Vue.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test TodoMVC_Angular
#     [Documentation]    Category: spa | URL: https://todomvc.com/examples/angular
#     [Tags]    spa    100websites
    
#     Open Website    https://todomvc.com/examples/angular
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=TodoMVC_Angular.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test React_Homepage
#     [Documentation]    Category: spa | URL: https://reactjs.org
#     [Tags]    spa    100websites
    
#     Open Website    https://reactjs.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=React_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Vue_Homepage
#     [Documentation]    Category: spa | URL: https://vuejs.org
#     [Tags]    spa    100websites
    
#     Open Website    https://vuejs.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Vue_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Angular_Homepage
#     [Documentation]    Category: spa | URL: https://angular.io
#     [Tags]    spa    100websites
    
#     Open Website    https://angular.io
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Angular_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Svelte_Homepage
#     [Documentation]    Category: spa | URL: https://svelte.dev
#     [Tags]    spa    100websites
    
#     Open Website    https://svelte.dev
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Svelte_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test NextJS_Homepage
#     [Documentation]    Category: spa | URL: https://nextjs.org
#     [Tags]    spa    100websites
    
#     Open Website    https://nextjs.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=NextJS_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test NuxtJS_Homepage
#     [Documentation]    Category: spa | URL: https://nuxtjs.org
#     [Tags]    spa    100websites
    
#     Open Website    https://nuxtjs.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=NuxtJS_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Gatsby_Homepage
#     [Documentation]    Category: spa | URL: https://www.gatsbyjs.com
#     [Tags]    spa    100websites
    
#     Open Website    https://www.gatsbyjs.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Gatsby_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Remix_Homepage
#     [Documentation]    Category: spa | URL: https://remix.run
#     [Tags]    spa    100websites
    
#     Open Website    https://remix.run
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Remix_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Astro_Homepage
#     [Documentation]    Category: spa | URL: https://astro.build
#     [Tags]    spa    100websites
    
#     Open Website    https://astro.build
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Astro_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Qwik_Homepage
#     [Documentation]    Category: spa | URL: https://qwik.builder.io
#     [Tags]    spa    100websites
    
#     Open Website    https://qwik.builder.io
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Qwik_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Solid_Homepage
#     [Documentation]    Category: spa | URL: https://solidjs.com
#     [Tags]    spa    100websites
    
#     Open Website    https://solidjs.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Solid_Homepage.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test HackerNews
#     [Documentation]    Category: social | URL: https://news.ycombinator.com
#     [Tags]    social    100websites
    
#     Open Website    https://news.ycombinator.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=HackerNews.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Reddit_Programming
#     [Documentation]    Category: social | URL: https://www.reddit.com/r/programming
#     [Tags]    social    100websites
    
#     Open Website    https://www.reddit.com/r/programming
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Reddit_Programming.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Reddit_WebDev
#     [Documentation]    Category: social | URL: https://www.reddit.com/r/webdev
#     [Tags]    social    100websites
    
#     Open Website    https://www.reddit.com/r/webdev
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Reddit_WebDev.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test StackOverflow
#     [Documentation]    Category: social | URL: https://stackoverflow.com
#     [Tags]    social    100websites
    
#     Open Website    https://stackoverflow.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=StackOverflow.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test GitHub_Explore
#     [Documentation]    Category: social | URL: https://github.com/explore
#     [Tags]    social    100websites
    
#     Open Website    https://github.com/explore
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=GitHub_Explore.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test GitHub_Trending
#     [Documentation]    Category: social | URL: https://github.com/trending
#     [Tags]    social    100websites
    
#     Open Website    https://github.com/trending
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=GitHub_Trending.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test ProductHunt
#     [Documentation]    Category: social | URL: https://www.producthunt.com
#     [Tags]    social    100websites
    
#     Open Website    https://www.producthunt.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=ProductHunt.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Lobsters
#     [Documentation]    Category: social | URL: https://lobste.rs
#     [Tags]    social    100websites
    
#     Open Website    https://lobste.rs
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Lobsters.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Slashdot
#     [Documentation]    Category: social | URL: https://slashdot.org
#     [Tags]    social    100websites
    
#     Open Website    https://slashdot.org
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Slashdot.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test IndieHackers
#     [Documentation]    Category: social | URL: https://www.indiehackers.com
#     [Tags]    social    100websites
    
#     Open Website    https://www.indiehackers.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=IndieHackers.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Amazon
#     [Documentation]    Category: ecommerce | URL: https://www.amazon.com
#     [Tags]    ecommerce    100websites
    
#     Open Website    https://www.amazon.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Amazon.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test eBay
#     [Documentation]    Category: ecommerce | URL: https://www.ebay.com
#     [Tags]    ecommerce    100websites
    
#     Open Website    https://www.ebay.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=eBay.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Etsy
#     [Documentation]    Category: ecommerce | URL: https://www.etsy.com
#     [Tags]    ecommerce    100websites
    
#     Open Website    https://www.etsy.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Etsy.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test AliExpress
#     [Documentation]    Category: ecommerce | URL: https://www.aliexpress.com
#     [Tags]    ecommerce    100websites
    
#     Open Website    https://www.aliexpress.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=AliExpress.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser

# Test Shopify
#     [Documentation]    Category: ecommerce | URL: https://www.shopify.com
#     [Tags]    ecommerce    100websites
    
#     Open Website    https://www.shopify.com
    
#     ${elements}=    Connector.Collect UI Candidates
#     Log Many    @{elements}
    
#     ${screenshot}=    Take Screenshot    filename=Shopify.png    fullPage=True
#     ${annotated}=    Draw And Log Elements    ${elements}    ${screenshot}
    
#     [Teardown]    Close Browser
